account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path('profile/<str:username>/', views.user_profile, name='user_profile'),
    path('profile/<str:username>/comments', views.user_profile_comments, name='user_profile_comments'),
    path("change_pass/", views.change_pass, name="change_pass"),
    path('update_profile/', views.update_profile, name='update_profile'),
]

insync_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('account/', include('account.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path("", views.home, name="home"), 
    path('<int:post_id>/', views.post_detail, name='post_detail'), 
    path('search/', views.search_result, name='search_result'),
    path('tag/<int:tag_id>/', views.category, name='category'),

    path('create_post/', views.create_post, name='create_post'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete/<int:post_id>/', views.delete_post, name='delete_post'),
    
    path('<int:post_id>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:post_id>/edit_comment/', views.edit_comment, name='edit_comment'),
    path('<int:post_id>/delete_comment/', views.delete_comment, name='delete_comment'),
    path('<int:post_id>/sort_comments/', views.sort_comments, name='sort_comments'),

    path('toggle_save/<str:object>/<int:object_id>/', views.toggle_save, name='toggle_save'),
    path('toggle_upvote/<str:object>/<int:object_id>/', views.toggle_upvote, name='toggle_upvote'),
    path('flag/<str:object>/<int:object_id>/', views.flag, name='flag'),

    path('all_posts/<int:user_id>/', views.all_posts, name='all_posts'),
    path('liked_posts/', views.liked_posts, name='liked_posts'),
    path('saved_posts/', views.saved_posts, name='saved_posts'),
    path('saved_comments/', views.saved_comments, name='saved_comments'),
    path('liked_comments/', views.liked_comments, name='liked_comments'),
]

posts/forms.py
from django import forms
from .models import Post, Media

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'url', 'tags'] 
        widgets = {
            'tags': forms.CheckboxSelectMultiple(attrs={'class': 'custom-checkbox'}),
            'title': forms.TextInput(attrs={'placeholder': 'Enter the title of the post'}),
            'content': forms.Textarea(attrs={'placeholder': 'Write your content here'}),
            'url': forms.URLInput(attrs={'placeholder': 'Optional URL for the post'}),
        }


class MediaForm(forms.ModelForm):
    class Meta:
        model = Media
        fields = ['media'] 

    def clean_media(self):
        media = self.cleaned_data.get('media')
        valid_extensions = {'.jpg', '.jpeg', '.png', '.gif', 'avif', 'webp', '.mp4', '.mov', '.webm'}
        if media and not any(media.name.lower().endswith(ext) for ext in valid_extensions):
            raise forms.ValidationError("File type not supported")
        return media

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .helpers import user_interaction_state, sort_queries, paginate
from django.contrib.auth.decorators import login_required
from django.middleware.csrf import get_token
from django.template.loader import render_to_string
from .models import Post, Comment, Save, Upvote, Flag, Tag
from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from .forms import PostForm, MediaForm
from django.http import HttpResponse
from django.contrib import messages
from itertools import chain


def home(request):
    post = Post.objects.all().order_by('-created_at')
    posts = paginate(request, post)
    context = { "posts": posts }
    return render(request, "posts/home.html", context)


@login_required
def create_post(request):
    if request.method == "POST":
        post_form = PostForm(request.POST)
        media_form = MediaForm(request.POST, request.FILES)
        if post_form.is_valid() and media_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
            media = media_form.save(commit=False)
            media.post = post
            media.save()
            post_form.save_m2m()
            messages.success(request, "You have created a post")
            return redirect('posts:post_detail', post_id=post.id)
    else:
        post_form = PostForm()
        media_form = MediaForm()
    context = { 'post_form': post_form, 'media_form': media_form, 'action': 'Create' }
    return render(request, 'posts/create_post.html', context)


def toggle_upvote(request, object, object_id):
    if not request.user.is_authenticated:
        return JsonResponse({'redirect': '/account/login/'}, status=401)
    if object == 'post':
        post = get_object_or_404(Post, id=object_id)
        upvote = Upvote.objects.filter(user=request.user, post=post).first()
    elif object == 'comment':
        comment = get_object_or_404(Comment, id=object_id)
        upvote = Upvote.objects.filter(user=request.user, comment=comment).first()
    else:
        return HttpResponse(status=400)
    
    if upvote:
        upvote.delete()
        if object == 'post':
            upvotes = post.upvote_count() 
        elif object == 'comment':
            upvotes = comment.upvote_count() 

        return JsonResponse(
            {
                'is_added': False, 
                'message': 'Unliked',
                'action': 'upvote', 
                'upvotes': upvotes 
            }
        )
    else:
        if object == 'post':
            Upvote.objects.create(user=request.user, post=post) 
            upvotes = post.upvote_count()  
        elif object == 'comment':
            Upvote.objects.create(user=request.user, comment=comment)  
            upvotes = comment.upvote_count() 

    return JsonResponse(
        {
            'is_added': True, 
            'message': 'Liked',
            'action': 'upvote', 
            'upvotes': upvotes 
        }
    )


def flag(request, object, object_id):
    if not request.user.is_authenticated:
        return JsonResponse({'redirect': '/account/login/'}, status=401)
    if object == 'post':
        post = get_object_or_404(Post, id=object_id)
        flag = Flag.objects.filter(user=request.user, post=post).first()
    elif object == 'comment':
        comment = get_object_or_404(Comment, id=object_id)
        flag = Flag.objects.filter(user=request.user, comment=comment).first()
    else:
        return JsonResponse(status=400)
    
    if request.method == 'POST':
        reason = request.POST.get('reason')
        if not reason:
            return
        if flag:
            flag.reason = reason
            flag.save()
            return JsonResponse(
                {
                    'message': 'Flag updated successfully', 
                    'action': 'flag'
                }
            )
        else:
            if object == 'post':
                flag = Flag.objects.create(
                    user=request.user, 
                    post=post, 
                    reason=reason
                )
            elif object == 'comment':
                flag = Flag.objects.create(
                    user=request.user, 
                    comment=comment, 
                    reason=reason
                )
            return JsonResponse({'message': 'Flagged successfully', 'action': 'flag'})
    return JsonResponse({'error': 'Invalid request method'}, status=405)


def toggle_save(request, object, object_id):
    if not request.user.is_authenticated:
        return JsonResponse({'redirect': '/account/login/'}, status=401)
    if object == 'post':
        post = get_object_or_404(Post, id=object_id)
        save = Save.objects.filter(user=request.user, post=post).first()
    elif object == 'comment':
        comment = get_object_or_404(Comment, id=object_id)
        save = Save.objects.filter(user=request.user, comment=comment).first()  
    else:
        return HttpResponse(status=400)
    if save:
        save.delete() 
        return JsonResponse(
            { 
                'is_added': False, 
                'message': 'Unsaved', 
                'action': 'save'
            }
        )
    else:
        if object == 'post':
            Save.objects.create(user=request.user, post=post)
        elif object == 'comment':
            Save.objects.create(user=request.user, comment=comment)  
    return JsonResponse(
        { 
            'is_added': True, 
            'message': 'Saved', 
            'action': 'save' 
        }
    )


@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    sort_by = request.GET.get('sort', 'upvotes')
    top_level_comments = post.comments.filter(parent__isnull=True)
    sorted_comments = sort_queries(top_level_comments, sort_by, 'comment_upvotes')
    comments = paginate(request, sorted_comments)

    context = {
        "post": post,
        "comments": comments,
        'sort_by': sort_by,
    }

    return render(request, "posts/post_detail.html", context)


@login_required
def sort_comments(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    sort_by = request.GET.get('sort', 'upvotes')  
    top_level_comments = post.comments.filter(parent__isnull=True)
    sorted_comments = sort_queries(top_level_comments, sort_by, 'comment_upvotes')
    comments = paginate(request, sorted_comments) 

    interaction = user_interaction_state(request.user)
    comments_list = render_to_string('partials/comment_list.html', 
        {
            'comments': comments,
            'user': request.user,
            'csrf_token': get_token(request),
            'interaction': interaction,
        }
    )

    return JsonResponse({'comments_list': comments_list})


def create_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if not request.user.is_authenticated:
        return JsonResponse({'redirect': '/account/login/'}, status=401)

    parent_comment_id = request.POST.get('parent_comment_id')
    parent_comment = None
    if parent_comment_id:
        parent_comment = get_object_or_404(Comment, id=parent_comment_id)

    text = request.POST.get('comment_text')
    if not text or text.strip() == '':
        return JsonResponse(status=400)

    comment = Comment.objects.create(
        post=post,
        user=request.user,
        parent=parent_comment,
        text=text
    )

    comment_html = render_to_string('partials/comment.html', 
        { 
            'comment': comment, 
            'user': request.user,
            'csrf_token': get_token(request),
        }
    )

    messages.success(request, 'Comment Posted!')
    flash_message_html = render_to_string('partials/flash_message.html', 
        {
            'messages': messages.get_messages(request),
        }
    )
    
    return JsonResponse(
        {
            'flash_message_html': flash_message_html,
            'comment_html': comment_html,
            'comment_id': comment.id,
            'action': 'create'
        }
    )


def edit_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if not request.user.is_authenticated:
        return JsonResponse({'redirect': '/account/login/'}, status=401)

    comment_id = request.POST.get('comment_id')
    comment = get_object_or_404(Comment, id=comment_id, user=request.user)
    new_text = request.POST.get('edit_comment_text')

    if not new_text or new_text.strip() == '':
        return JsonResponse({'error': 'New comment is required.'}, status=400)

    comment.text = new_text
    comment.save()

    interaction = user_interaction_state(request.user)
    comment_html = render_to_string('partials/comment.html', 
        { 
            'comment': comment,  
            'user': request.user,
            'csrf_token': get_token(request),
            'interaction': interaction,
        }
    )

    messages.success(request, 'Comment Edited!')
    flash_message_html = render_to_string('partials/flash_message.html', 
        {
            'messages': messages.get_messages(request),
        }
    )

    return JsonResponse(
        {
            'flash_message_html': flash_message_html,
            'comment_html': comment_html,
            'comment_id': comment.id,
            'action': 'edit'
        }
    )


def delete_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if not request.user.is_authenticated:
        return JsonResponse({'redirect': '/account/login/'}, status=401)

    comment_id = request.POST.get('comment_id')
    comment = get_object_or_404(Comment, id=comment_id, user=request.user)
    comment.delete()

    messages.success(request, 'Comment Deleted!')
    flash_message_html = render_to_string('partials/flash_message.html', 
        {

posts/templates/partials/comment.html
<div>
<li id="comment-{{ comment.id }}" class="ea-comment"> 
    <input type="checkbox" class="toggle-checkbox" id="toggle-comments{{ comment.id }}" style="display: none;">
    <label for="toggle-comments{{ comment.id }}" class="toggle-btn">
        <i class="fa-solid fa-square-plus"></i>
        <i class="fa-solid fa-square-minus"></i>
    </label> 
    <div class="comment-container flex"> 
        <div class="left">
            <a href="{% url 'account:user_profile' comment.user.username %}">
                {% include "partials/profile_img.html" with post=comment %}
            </a>            
        </div>
        <div class="right">
            <div class="comment-head flex">
                <div class="flex">
                    <a class="user_profile" href="{% url 'account:user_profile' comment.user.username %}">
                       <strong>{{ comment.user.username }}</strong>
                    </a> 
                    {% load custom_filters %}
                    <small>{{ comment.created_at|shortened_timesince }} ago</small>
                </div>
                {% include "partials/comment_interaction.html" %}
            </div>
            <p class="comment-content">{{ comment.text }}</p>
            {% include "partials/comment_interaction2.html" %}
        </div>
    </div>
    {% if comment.replies.exists %}
    <ul style="margin-left: 30px;" id="replies-{{ comment.id }}" class="comment-replies">
    {% for reply in comment.replies.all %}
        {% include "partials/comment.html" with comment=reply %}
    {% endfor %}
    </ul>
    {% endif %}
</li>
</div>

posts/templates/partials/comment_interaction.html
<div class="comment-interaction flex">
    <form 
        method="POST" 
        action="{% url 'posts:toggle_save' 'comment' comment.id %}" 
        class="action-form">
        {% csrf_token %}
        <button class="interaction-btn" type="submit">
            {% if comment.id in interaction.comments.saved %}
            <i class="fa-solid fa-bookmark"></i>
            {% else %}
            <i class="fa-regular fa-bookmark"></i>
            {% endif %}
        </button>
    </form>

    <details name="reqs" class="flag">
        <summary><i class="fa-regular fa-flag"></i></summary>
        <form 
            method="POST" 
            action="{% url 'posts:flag' 'comment' comment.id %}" 
            class="action-form">
            {% csrf_token %}
            <label>
                <input type="radio" name="reason" value="spam"> Spam
            </label>
            <label>
                <input type="radio" name="reason" value="abuse"> Abuse
            </label>
            <label>
                <input type="radio" name="reason" value="harassment"> Harassment
            </label>
            <label>
                <input type="radio" name="reason" value="misinformation"> Misinformation
            </label>
            <label>
                <input type="radio" name="reason" value="other"> Other
            </label>
            <button class="blue-btn" type="submit">Flag</button>
        </form>
    </details>

    {% if comment.user == user %}
    <form 
        method="POST" 
        action="{% url 'posts:delete_comment' comment.post.id %}" 
        class="action-form">
        {% csrf_token %}
        <input type="hidden" name="comment_id" value="{{ comment.id }}">
        <button class="interaction-btn" type="submit" name="delete_comment"> <i class="fa-solid fa-delete-left"></i></button>
    </form>
    {% endif %}
</div>

posts/templates/partials/comment_interaction2.html
<div class="comment-interaction flex">
    <form 
        method="POST" 
        action="{% url 'posts:toggle_upvote' 'comment' comment.id %}" 
        class="like action-form">
        {% csrf_token %}
        <button class="interaction-btn" type="submit">
            {% if comment.id in interaction.comments.upvoted %}
            <i class="fa-solid fa-heart"></i> 
            <p class="likes-count">{{ comment.upvote_count }}</p>
            {% else %}
            <i class="fa-regular fa-heart"></i> 
            <p class="likes-count">{{ comment.upvote_count }}</p>
            {% endif %}
        </button>
    </form>

    <details id="replyDetails" name="reqs" style="margin-left: 20px;">
        <summary>
            <i class="fa-regular fa-comment"></i>
        </summary>
        <form 
            method="POST" 
            action="{% url 'posts:create_comment' comment.post.id %}" 
            class="reply action-form">
            {% csrf_token %}
            <textarea 
                name="comment_text" id="comment_text"
                required>
            </textarea>
            <input type="hidden" name="parent_comment_id" value="{{ comment.id }}"> 
            <div class="bottom">
                <div class='cancel-btn'>Cancel</div>
                <button class="blue-btn" type="submit" name="create_comment">Reply</button>
            </div> 
        </form>
    </details>

    {% if comment.user == user %}
    <details name="reqs">
        <summary>
            <i class="fa-regular fa-pen-to-square"></i>
        </summary>
        <form 
            method="POST" 
            action="{% url 'posts:edit_comment' comment.post.id %}" 
            class="edit action-form">
            {% csrf_token %}
            <textarea name="edit_comment_text" id="edit_comment_text" required>{{ comment.text }}</textarea>
            <input type="hidden" name="comment_id" value="{{ comment.id }}">
            <div class="bottom">
                <div class='cancel-btn'>Cancel</div>
                <button class="blue-btn" type="submit" name="edit_comment">Edit</button>
            </div> 
        </form>
    </details>
    {% endif %}
</div>

posts/templates/partials/comment_list.html
{% for comment in comments %} 
{% include "partials/comment.html" %} 
{% endfor %}

posts/templates/partials/comment_search.html
<section class="comment-results">
    <div class="container">
        <div class="top-flex flex">
            <div class="left">
                <a href="{% url 'account:user_profile' comment.user.username %}">
                    {% include "partials/profile_img.html" with post=comment %}
                </a> 
            </div>
            <div class="right">
                <div class="content-wrapper">
                    <div class="comment-head flex">
                        <div class="flex">
                            <a class="user_profile" href="{% url 'account:user_profile' comment.user.username %}">
                            <strong>{{ comment.user.username }}</strong> 
                            </a> 
                            {% load custom_filters %}
                            <small>{{ comment.created_at|shortened_timesince }} ago</small>
                        </div>
                        {% include "partials/comment_interaction.html" %}
                    </div>
                    {% if comment.text %}
                    <h3 class="post-title">
                        <a href="{% url 'posts:post_detail' comment.post.id %}">{{ comment.post.title }}</a>
                    </h3>
                    <p>{{ comment.text }}</p>
                    {% endif %}
                    <div class="comment-interaction">
                        <form 
                            method="POST" 
                            action="{% url 'posts:toggle_upvote' 'comment' comment.id %}" 
                            class="like action-form">
                            {% csrf_token %}
                            <button class="interaction-btn" type="submit">
                                {% if comment.id in interaction.comments.upvoted %}
                                <i class="fa-solid fa-heart"></i> 
                                <p class="likes-count">{{ comment.upvote_count }}</p>
                                {% else %}
                                <i class="fa-regular fa-heart"></i> 
                                <p class="likes-count">{{ comment.upvote_count }}</p>
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <hr>
    </div>
</section>

posts/templates/partials/detail_sort.html
<select name="sort" id="sort-detail" class="sort" data-post-id="{{ post.id }}">
    <option value="newest">Newest</option>
    <option value="oldest">Oldest</option>
    <option value="upvotes">Most Liked</option>
    <option value="-upvotes">Least Liked</option>
</select>

posts/templates/partials/flash_message.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div class="flash-message">
        <p class="flash-text">{{ message }}</p>
        <i class="fa-solid fa-xmark"></i>
    </div>
    {% endfor %}
</div>
{% endif %}

posts/templates/partials/main_search.html
<form action="{% url 'posts:search_result' %}" method="GET" class="search-form">
    <i class="fa-solid fa-magnifying-glass"></i>
    <input required type="text" name="query" placeholder="Search Posts, Comments or Tags" value="{{ request.GET.query }}">
    {% include "partials/sort.html" %}
</form>

posts/templates/partials/media_post.html
{% if post.first_media and post.first_media.media %}
<div class="media">
    {% if post.first_media.is_video %}
    <video controls class="media-content">
        <source src="{{ MEDIA_URL }}{{ post.first_media.media.url }}" type="video/mp4" />
    </video>
    {% else %}
    <div
        class="media-content"
        style="background-image: url('{{ MEDIA_URL }}{{ post.first_media.media.url }}');">
    </div>
    {% endif %}
</div>
{% endif %}

posts/templates/partials/pagination.html
<section class="pagination">
    <div class="container">
        <span class="step-links">
            <div>
                {% if posts.has_previous %}
                <a class="blue-btn" href="?page=1">&laquo; First</a>
                <a class="blue-btn" href="?page={{ posts.previous_page_number }}">Previous</a>
                {% endif %}
            </div>
            {% if posts.has_previous or posts.has_next %}
            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}
            </span>
            {% endif %}
            <div>
                {% if posts.has_next %}
                <a class="blue-btn" href="?page={{ posts.next_page_number }}">Next</a>
                <a class="blue-btn" href="?page={{ posts.paginator.num_pages }}">Last &raquo;</a>
                {% endif %}
            </div>
        </span>
    </div>
</section>

posts/templates/partials/post.html
<div class="post-container flex">
    <div class="left">
        <a href="{% url 'account:user_profile' post.user.username %}">
            {% include "partials/profile_img.html" %}
        </a>
    </div>
    <div class="right">
        <div class="post-head flex">
            <div class="flex">
                <a class="user_profile" href="{% url 'account:user_profile' post.user.username %}">
                    <strong>{{ post.user.username }}</strong>
                </a>
                {% load custom_filters %}
                <p>{{ post.created_at|shortened_timesince }} ago</p>
            </div>
            {% include "partials/post_interactions.html" %} 
        </div>
        {% if post.title %}
        <h2 class="post-title">
            <a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a>
        </h2>
        {% endif %}

        <div class="tags flex">
        {% for tag in post.tags.all %}
            <p><a class="tags-urls" href="{% url 'posts:category' tag.id %}">{{ tag.name }}</a>,</p>
        {% endfor %}
        </div>

        <div class="content">
            {% if truncate %}
                {{ post.content|truncatewords:40|safe }}
            {% else %}
                {{ post.content|safe }}
            {% endif %}
        </div>

        {% include "partials/media_post.html" %} 

        <div class="url-container">
            {% if post.url %}
            <a 
                class="post-url tags-urls"
                target="_blank" 
                href="{{ post.url }}">
                <i class="fa-solid fa-link"></i>{{ post.url }}
            </a>
            {% endif %}
        </div>
        {% include "partials/post_interactions2.html" with post_id=post.id %}
    </div>
</div>

posts/templates/partials/post_interactions.html
<div class="interaction flex">
    <form 
        method="POST" 
        action="{% url 'posts:toggle_save' 'post' post.id %}" 
        class="action-form save">
        {% csrf_token %}
        <button class="interaction-btn" type="submit">
            {% if post.id in interaction.posts.saved %}
            <i class="fa-solid fa-bookmark"></i>
            {% else %}
            <i class="fa-regular fa-bookmark"></i>
            {% endif %}
        </button>
    </form>

    <details name="reqs" class="flag">
        <summary>
            <i class="fa-regular fa-flag"></i>
        </summary>
        <form 
            method="POST" 
            action="{% url 'posts:flag' 'post' post.id %}" 
            class="action-form">
            {% csrf_token %}
            <label>
                <input type="radio" name="reason" value="spam"> Spam
            </label>
            <label>
                <input type="radio" name="reason" value="abuse"> Abuse
            </label>
            <label>
                <input type="radio" name="reason" value="harassment"> Harassment
            </label>
            <label>
                <input type="radio" name="reason" value="misinformation"> Misinformation
            </label>
            <label>
                <input type="radio" name="reason" value="other"> Other
            </label>
            <button class="blue-btn" type="submit">Flag</button>
        </form>
    </details>
    {% if post.user == request.user %}
    <div 
        id="delete-btn" 
        class="btn-yellow"
        data-post-id="{{ post.id }}"
        >
        Delete
    </div>

    <div class="popup-box" id="popup" data-post-id="{{ post.id }}">
		<div class="popup-content">
        {% include "posts/delete_post.html" with post_id=post.id %}
		</div>
	</div>
    {% endif %}
</div>

posts/templates/partials/post_search.html
<section class="post-results">
    <div class="container">
        <div class="top-flex">
            <div class="main-wrapper">
                <div class="left">
                    <a href="{% url 'account:user_profile' post.user.username %}">
                        {% include "partials/profile_img.html" %} 
                    </a>
                </div>
                <div class="right">
                    <div class="post-head flex">
                        <a class="user_profile" href="{% url 'account:user_profile' post.user.username %}">
                            <strong>{{ post.user.username }}</strong>
                        </a>
                        {% load custom_filters %}
                        <small>{{ post.created_at|shortened_timesince }} ago</small>
                    </div>
                    {% if post.title %}
                    <h2 class="post-title">
                        <a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a>
                    </h2>
                    {% endif %}
                    <div class="tags flex">
                    {% for tag in post.tags.all %}
                        <p><a class="tags-urls" href="{% url 'posts:category' tag.id %}">{{ tag.name }}</a>, </p>
                    {% endfor %}
                    </div>
                    {% include "partials/post_interactions2.html" %}
                </div>
            </div>
            {% include "partials/media_post.html" %}
        </div>  
        <hr>
    </div>
</section>

posts/templates/partials/profile_img.html
{% if post.user.profile.profile_image %}
<div
    class="profile-img"
    style="background-image: url('{{ post.user.profile.profile_image.url }}');"
></div>
{% else %}
<div class="no-img">
    <i class="fa-regular fa-user"></i>
</div>
{% endif %}