account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path('profile/<str:username>/', views.user_profile, name='user_profile'),
    path('profile/<str:username>/comments', views.user_profile_comments, name='user_profile_comments'),
    path("change_pass/", views.change_pass, name="change_pass"),
    path('update_profile/', views.update_profile, name='update_profile'),
]

insync_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('account/', include('account.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path("", views.home, name="home"), 
    path('<int:post_id>/', views.post_detail, name='post_detail'), 
    path('search/', views.search_result, name='search_result'),
    path('tag/<int:tag_id>/', views.category, name='category'),

    path('create_post/', views.create_post, name='create_post'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete/<int:post_id>/', views.delete_post, name='delete_post'),
    
    path('<int:post_id>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:post_id>/edit_comment/', views.edit_comment, name='edit_comment'),
    path('<int:post_id>/delete_comment/', views.delete_comment, name='delete_comment'),
    path('<int:post_id>/sort_comments/', views.sort_comments, name='sort_comments'),

    path('toggle_save/<str:object>/<int:object_id>/', views.toggle_save, name='toggle_save'),
    path('toggle_upvote/<str:object>/<int:object_id>/', views.toggle_upvote, name='toggle_upvote'),
    path('flag/<str:object>/<int:object_id>/', views.flag, name='flag'),

    path('all_posts/<int:user_id>/', views.all_posts, name='all_posts'),
    path('liked_posts/', views.liked_posts, name='liked_posts'),
    path('saved_posts/', views.saved_posts, name='saved_posts'),
    path('saved_comments/', views.saved_comments, name='saved_comments'),
    path('liked_comments/', views.liked_comments, name='liked_comments'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.CharField(max_length=255, blank=True, null=True)
    profile_image = models.FileField(upload_to='', blank=True, null=True)
    job_title = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f'Profile user: {self.user.username}'
    
    def first_profile_image(self):
        return self.profile_image if self.profile_image else None

account/forms.py
from django import forms
from .models import Profile

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['email', 'job_title']

class ProfileImage(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_image']

    def clean_profile_image(self):
        image = self.cleaned_data.get('profile_image')
        if image:
            valid_extensions = ['.jpg', '.jpeg', '.png', '.gif']
            if image and not any(image.name.lower().endswith(ext) for ext in valid_extensions):
                raise forms.ValidationError("File type not supported")
        return image

account/views.py
from django.contrib.auth import login as django_login, logout as django_logout
from django.contrib.auth.decorators import login_required
from .forms import ProfileUpdateForm, ProfileImage
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from posts.helpers import paginate
from django.contrib import messages
from posts.models import Post, Comment
from .models import Profile
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    SetPasswordForm,
)
import os

@login_required
def change_pass(request):
    user = request.user
    if request.method == "POST":
        form = SetPasswordForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Password changed successfully please login!")
            return redirect("account:login")
    else:
        form = SetPasswordForm(user=request.user)
    context = {"form": form, 'user': user }
    return render(request, "account/change_pass.html", context)


def signup(request):
    form = UserCreationForm(request.POST)
    context = {"form": form}
    if request.method == "GET" or not form.is_valid():
        return render(request, "account/signup.html", context)
    user = form.save()
    profile = Profile.objects.create(user=user)
    if user.is_superuser:
        profile.job_title = 'Admin'  
        profile.save()
    messages.success(request, "Account created, please login!")
    return redirect("account:login")

    
def login(request):
    form = AuthenticationForm(request, data=request.POST)
    context = {"form": form}
    if request.method == "GET" or not form.is_valid():
        return render(request, "account/login.html", context)
    user = form.get_user()
    django_login(request, user)
    messages.success(request, "Welcome, post something cool")
    return redirect("posts:home")


@login_required
def update_profile(request):
    profile = request.user.profile
    if request.method == "POST":
        form = ProfileUpdateForm(request.POST, instance=profile)
        profile_img = ProfileImage(request.POST, request.FILES, instance=profile)
        if form.is_valid() and profile_img.is_valid():
            if request.FILES.get('profile_image'):
                new_image = request.FILES['profile_image']
                if profile.profile_image:
                    old_image_path = profile.profile_image.path
                    if os.path.isfile(old_image_path):
                        os.remove(old_image_path)
                profile.profile_image = new_image
            form.save()
            profile_img.save()
            messages.success(request, "Profile Updated Successfully")
            return redirect("account:update_profile")
    else:
        form = ProfileUpdateForm(instance=profile)
        profile_img = ProfileImage(instance=profile)
    context = {'form': form, 'profile_img': profile_img, 'profile': profile}
    return render(request, 'account/update_profile.html', context)


@login_required
def user_profile(request, username):
    user = get_object_or_404(User, username=username)
    post = Post.objects.filter(user=user).order_by('-created_at')
    posts = paginate(request, post)

    context = {
        'profile_user': user,
        'posts': posts,
    }

    return render(request, 'account/user_profile.html', context)


@login_required
def user_profile_comments(request, username):
    user = get_object_or_404(User, username=username)
    comment = Comment.objects.filter(user=user).order_by('-created_at')
    comments = paginate(request, comment)

    context = {
        'profile_user': user,
        'comments': comments,
    }

    return render(request, 'account/user_profile_comments.html', context)


def logout(request):
    django_logout(request)
    return redirect("account:login")

account/templates/acc_partials/profile_image.html
{% if request.user.profile.profile_image %}
<div
    class="profile-img"
    style="background-image: url('{{ request.user.profile.profile_image.url }}');">
</div>
{% else %}
<div class="no-img">
    <i class="fa-regular fa-user"></i>
</div>
{% endif %}

account/templates/acc_partials/profile_overview.html
<section class="profile-overview">
    <div class="container">
        <div class="flex">
            <div class="left">
                <div class="profile-container">
                    {% include "acc_partials/profile_image.html" %}
                    <div>
                        <p>{{ user.username }}</p>
                        {% if user.profile.email %}
                            <p>{{ user.profile.email }}</p>
                        {% else %}
                        <p>
                            Add
                            <a href="{% url 'account:update_profile' %}">
                                Email
                            </a>
                        </p>
                        
                        {% endif %}

                        {% if user.profile.job_title %}
                            <p>{{ user.profile.job_title }}</p>
                        {% else %}
                        <p>
                            Add
                            <a href="{% url 'account:update_profile' %}">
                                Job Title
                            </a> 
                        </p>
                       
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="right">
                <a class="btn-yellow" href="{% url 'account:update_profile' %}"
                    >Update</a
                >
                <a class="btn-red" href="{% url 'account:logout' %}">Logout</a>
            </div>
        </div>

        <div class="profile-links">
            <a
                class="btn-transparent"
                href="{% url 'posts:all_posts' user.id %}">
				All posts
			</a>
            <a 
				class="btn-transparent" 
				href="{% url 'posts:saved_posts' %}">
				Saved Posts
			</a>
            <a 
				class="btn-transparent" 
				href="{% url 'posts:liked_posts' %}">
				Liked posts
			</a>
            <a 
				class="btn-transparent" 
				href="{% url 'posts:saved_comments' %}">
				Saved Comments
			</a>
            <a 
				class="btn-transparent" 
				href="{% url 'posts:liked_comments' %}">
				Liked Comments
			</a>
            <a 
                class="btn-transparent" 
                href="{% url 'account:change_pass' %}">
                Password
            </a>
        </div>
        <hr>
    </div>
</section>