account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path('profile/<str:username>/', views.user_profile, name='user_profile'),
    path('profile/<str:username>/comments', views.user_profile_comments, name='user_profile_comments'),
    path("change_pass/", views.change_pass, name="change_pass"),
    path('update_profile/', views.update_profile, name='update_profile'),
]

insync_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('account/', include('account.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path("", views.home, name="home"), 
    path('<int:post_id>/', views.post_detail, name='post_detail'), 
    path('search/', views.search_result, name='search_result'),
    path('tag/<int:tag_id>/', views.category, name='category'),

    path('create_post/', views.create_post, name='create_post'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete/<int:post_id>/', views.delete_post, name='delete_post'),
    
    path('<int:post_id>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:post_id>/edit_comment/', views.edit_comment, name='edit_comment'),
    path('<int:post_id>/delete_comment/', views.delete_comment, name='delete_comment'),
    path('<int:post_id>/sort_comments/', views.sort_comments, name='sort_comments'),

    path('toggle_save/<str:object>/<int:object_id>/', views.toggle_save, name='toggle_save'),
    path('toggle_upvote/<str:object>/<int:object_id>/', views.toggle_upvote, name='toggle_upvote'),
    path('flag/<str:object>/<int:object_id>/', views.flag, name='flag'),

    path('all_posts/<int:user_id>/', views.all_posts, name='all_posts'),
    path('liked_posts/', views.liked_posts, name='liked_posts'),
    path('saved_posts/', views.saved_posts, name='saved_posts'),
    path('saved_comments/', views.saved_comments, name='saved_comments'),
    path('liked_comments/', views.liked_comments, name='liked_comments'),
]

posts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from .helpers import sort_queries
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import InMemoryUploadedFile


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(default=timezone.now) 

    def __str__(self):
        return f"{self.name}"


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    tags = models.ManyToManyField(Tag, related_name='post_tag')
    url = models.URLField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    @classmethod
    def search(cls, query, sort_by='upvotes_count'):
        query_conditions = Q(title__icontains=query) | Q(tags__name__icontains=query)
        posts = cls.objects.filter(query_conditions)
        return sort_queries(posts, sort_by, 'post_upvotes')

    def upvote_count(self):
        return self.post_upvotes.count()
    
    def first_media(self):
        return self.media_post.first() if self.media_post.exists() else None
    
    def top_level_comments_count(self):
        return self.comments.filter(parent=None).count()
    
    def total_comments(self):
        return self.comments.count()
    
    def flag_count(self):
        return self.flags.count()
    
    def __str__(self):
        return self.title
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)  
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='replies') 
    user = models.ForeignKey(User, related_name="comment_user", on_delete=models.CASCADE)
    text = models.TextField(max_length=200)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    @classmethod
    def search(cls, query, sort_by='-upvotes_count'):
        comments = cls.objects.filter(text__icontains=query)
        return sort_queries(comments, sort_by, 'comment_upvotes')

    def flag_count(self):
        return self.flags.count()

    def upvote_count(self):
        return self.comment_upvotes.count()
    
    def __str__(self):
        return f"Comment by {self.user} in Post: {self.post.title}"
    

def validate_file_size(value):
    max_size_mb = 5 
    limit = max_size_mb * 1024 * 1024
    if isinstance(value, InMemoryUploadedFile) and value.size > limit:
        raise ValidationError(f"File size exceeds the {max_size_mb} MB limit.")
    

class Media(models.Model):
    post = models.ForeignKey(Post, null=True, blank=True, related_name="media_post", on_delete=models.CASCADE) 
    media = models.FileField(upload_to='', null=True, blank=True, validators=[validate_file_size])
    uploaded_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        if self.post:
            return f"Media Post: {self.post} - ID: {self.post.id} - user: {self.post.user}"
        else:
            return "None"
    
    def is_video(self):
        if self.media:
            return self.media.name.lower().endswith(
                ('.mp4', '.mov', '.webm')
            )
        return False

     
class Upvote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name="post_upvotes", null=True, blank=True, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, related_name="comment_upvotes", null=True, blank=True, on_delete=models.CASCADE)
    upvoted_at = models.DateTimeField(default=timezone.now)

    unique_together = (
        ('user', 'post'),
        ('user', 'comment'),
    ) 

    def __str__(self):
        return f"Upvote by {self.user} for {'Post' if self.post else 'Comment'} ID {self.post.id if self.post else self.comment.id}"


class Save(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, null=True, blank=True, on_delete=models.CASCADE)
    saved_at = models.DateTimeField(default=timezone.now)

    unique_together = (
        ('user', 'post'),
        ('user', 'comment'),
    ) 

    def __str__(self):
        return f"Saved by {self.user} for {'Post' if self.post else 'Comment'} ID {self.post.id if self.post else self.comment.id}"


class Flag(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name="flags", null=True, blank=True, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, related_name="flags", null=True, blank=True, on_delete=models.CASCADE)
    reason = models.TextField()
    flagged_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    unique_together = (
        ('user', 'post'),
        ('user', 'comment'),
    ) 

    def __str__(self):
        return f"Flagged by {self.user} for {'Post' if self.post else 'Comment'} ID {self.post.id if self.post else self.comment.id}"

insync_platform/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block 'title' %}{% endblock %}</title>
    {% load static %}
    <script src="{% static 'tinymce/tinymce.min.js' %}"></script>
    <script type="module" src="{% static 'js/app.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link 
        rel="stylesheet" 
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" 
        crossorigin="anonymous" 
        referrerpolicy="no-referrer" 
    />
</head>

<body>
    <header class="main-header">
        <div class="container">
            <a class="logo" href="{% url 'posts:home' %}">
                <h3>inSync</h3>
            </a>
            {% if request.path != '/account/login/' and request.path != '/account/signup/' %}
            {% include "partials/main_search.html" %}
            <div class="search-icon">
                <i class="fa-solid fa-magnifying-glass"></i>
            </div>
            {% endif %}
            <div class="holder">
                <nav>
                    <ul class="home-icon"> 
                        <li><a href="{% url 'posts:home' %}">Home</a></li>
                    </ul>
                </nav>
                {% if request.user.is_authenticated %}
                <ul class="profile">
                    <li class="create-post">
                        <a class="btn-yellow" href="{% url 'posts:create_post' %}">Post
                            <i class="fa-solid fa-plus"></i>
                        </a>
                    </li>
                    <li>
                        <a class="profile-acc" href="{% url 'account:update_profile'%}">
                            {% include "acc_partials/profile_image.html" %}
                        </a>
                    </li>
                </ul>
                {% else %}   
                <ul class="logs">
                    <li><a href="{% url 'account:signup' %}">Signup</a></li>
                    <span>/</span>
                    <li><a href="{% url 'account:login' %}">Login</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
    </header>
    <header class="search-header" style="display: none;">
        <div class="container">
            <div class="back-btn" id="back-btn">Back</div>
            {% if request.path != '/account/login/' and request.path != '/account/signup/' %}
            {% include "partials/main_search.html" %}
            {% endif %}
        </div>
    </header>

    <main>{% block 'main' %}{% endblock %}</main>

    <footer>
        inSync 2025. All rights reserved
    </footer>
    <script>
        tinymce.init({
        selector: '#id_content',
        license_key: 'gpl',
        plugins: 'lists',
        toolbar: 'bold italic underline | alignleft aligncenter alignright | bullist numlist',  
        menubar: false,
        content_css: '{% static "css/app.css" %}',
        drag_drop_upload: false, 
        paste_data_images: false,
    });
    </script>
</body>
</html>