insync_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('account/', include('account.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path("", views.home, name="home"), 
    path('<int:post_id>/', views.post_detail, name='post_detail'), 
    path('search/', views.search_result, name='search_result'),
    path('tag/<int:tag_id>/', views.category, name='category'),

    path('create_post/', views.create_post, name='create_post'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete/<int:post_id>/', views.delete_post, name='delete_post'),
    
    path('<int:post_id>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:post_id>/edit_comment/', views.edit_comment, name='edit_comment'),
    path('<int:post_id>/delete_comment/', views.delete_comment, name='delete_comment'),
    path('<int:post_id>/sort_comments/', views.sort_comments, name='sort_comments'),

    path('toggle_save/<str:object>/<int:object_id>/', views.toggle_save, name='toggle_save'),
    path('toggle_upvote/<str:object>/<int:object_id>/', views.toggle_upvote, name='toggle_upvote'),
    path('flag/<str:object>/<int:object_id>/', views.flag, name='flag'),

    path('all_posts/<int:user_id>/', views.all_posts, name='all_posts'),
    path('liked_posts/', views.liked_posts, name='liked_posts'),
    path('saved_posts/', views.saved_posts, name='saved_posts'),
    path('saved_comments/', views.saved_comments, name='saved_comments'),
    path('liked_comments/', views.liked_comments, name='liked_comments'),
]

posts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from .helpers import sort_queries
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import InMemoryUploadedFile


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(default=timezone.now) 

    def __str__(self):
        return f"{self.name}"


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    tags = models.ManyToManyField(Tag, related_name='post_tag')
    url = models.URLField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    @classmethod
    def search(cls, query, sort_by='upvotes_count'):
        query_conditions = Q(title__icontains=query) | Q(tags__name__icontains=query)
        posts = cls.objects.filter(query_conditions)
        return sort_queries(posts, sort_by, 'post_upvotes')

    def upvote_count(self):
        return self.post_upvotes.count()
    
    def first_media(self):
        return self.media_post.first() if self.media_post.exists() else None
    
    def top_level_comments_count(self):
        return self.comments.filter(parent=None).count()
    
    def total_comments(self):
        return self.comments.count()
    
    def flag_count(self):
        return self.flags.count()
    
    def __str__(self):
        return self.title
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)  
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='replies') 
    user = models.ForeignKey(User, related_name="comment_user", on_delete=models.CASCADE)
    text = models.TextField(max_length=200)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    @classmethod
    def search(cls, query, sort_by='-upvotes_count'):
        comments = cls.objects.filter(text__icontains=query)
        return sort_queries(comments, sort_by, 'comment_upvotes')

    def flag_count(self):
        return self.flags.count()

    def upvote_count(self):
        return self.comment_upvotes.count()
    
    def __str__(self):
        return f"Comment by {self.user} in Post: {self.post.title}"
    

def validate_file_size(value):
    max_size_mb = 5 
    limit = max_size_mb * 1024 * 1024
    if isinstance(value, InMemoryUploadedFile) and value.size > limit:
        raise ValidationError(f"File size exceeds the {max_size_mb} MB limit.")
    

class Media(models.Model):
    post = models.ForeignKey(Post, null=True, blank=True, related_name="media_post", on_delete=models.CASCADE) 
    media = models.FileField(upload_to='', null=True, blank=True, validators=[validate_file_size])
    uploaded_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        if self.post:
            return f"Media Post: {self.post} - ID: {self.post.id} - user: {self.post.user}"
        else:
            return "None"
    
    def is_video(self):
        if self.media:
            return self.media.name.lower().endswith(
                ('.mp4', '.mov', '.webm')
            )
        return False

     
class Upvote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name="post_upvotes", null=True, blank=True, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, related_name="comment_upvotes", null=True, blank=True, on_delete=models.CASCADE)
    upvoted_at = models.DateTimeField(default=timezone.now)

    unique_together = (
        ('user', 'post'),
        ('user', 'comment'),
    ) 

    def __str__(self):
        return f"Upvote by {self.user} for {'Post' if self.post else 'Comment'} ID {self.post.id if self.post else self.comment.id}"


class Save(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, null=True, blank=True, on_delete=models.CASCADE)
    saved_at = models.DateTimeField(default=timezone.now)

    unique_together = (
        ('user', 'post'),
        ('user', 'comment'),
    ) 

    def __str__(self):
        return f"Saved by {self.user} for {'Post' if self.post else 'Comment'} ID {self.post.id if self.post else self.comment.id}"


class Flag(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name="flags", null=True, blank=True, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, related_name="flags", null=True, blank=True, on_delete=models.CASCADE)
    reason = models.TextField()
    flagged_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    unique_together = (
        ('user', 'post'),
        ('user', 'comment'),
    ) 

    def __str__(self):
        return f"Flagged by {self.user} for {'Post' if self.post else 'Comment'} ID {self.post.id if self.post else self.comment.id}"

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .helpers import user_interaction_state, sort_queries, paginate
from django.contrib.auth.decorators import login_required
from django.middleware.csrf import get_token
from django.template.loader import render_to_string
from .models import Post, Comment, Save, Upvote, Flag, Tag
from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from .forms import PostForm, MediaForm
from django.http import HttpResponse
from django.contrib import messages
from itertools import chain


def home(request):
    post = Post.objects.all().order_by('-created_at')
    posts = paginate(request, post)
    context = { "posts": posts }
    return render(request, "posts/home.html", context)


@login_required
def create_post(request):
    if request.method == "POST":
        post_form = PostForm(request.POST)
        media_form = MediaForm(request.POST, request.FILES)
        if post_form.is_valid() and media_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
            media = media_form.save(commit=False)
            media.post = post
            media.save()
            post_form.save_m2m()
            messages.success(request, "You have created a post")
            return redirect('posts:post_detail', post_id=post.id)
    else:
        post_form = PostForm()
        media_form = MediaForm()
    context = { 'post_form': post_form, 'media_form': media_form, 'action': 'Create' }
    return render(request, 'posts/create_post.html', context)


def toggle_upvote(request, object, object_id):
    if not request.user.is_authenticated:
        return JsonResponse({'redirect': '/account/login/'}, status=401)
    if object == 'post':
        post = get_object_or_404(Post, id=object_id)
        upvote = Upvote.objects.filter(user=request.user, post=post).first()
    elif object == 'comment':
        comment = get_object_or_404(Comment, id=object_id)
        upvote = Upvote.objects.filter(user=request.user, comment=comment).first()
    else:
        return HttpResponse(status=400)
    
    if upvote:
        upvote.delete()
        if object == 'post':
            upvotes = post.upvote_count() 
        elif object == 'comment':
            upvotes = comment.upvote_count() 

        return JsonResponse(
            {
                'is_added': False, 
                'message': 'Unliked',
                'action': 'upvote', 
                'upvotes': upvotes 
            }
        )
    else:
        if object == 'post':
            Upvote.objects.create(user=request.user, post=post) 
            upvotes = post.upvote_count()  
        elif object == 'comment':
            Upvote.objects.create(user=request.user, comment=comment)  
            upvotes = comment.upvote_count() 

    return JsonResponse(
        {
            'is_added': True, 
            'message': 'Liked',
            'action': 'upvote', 
            'upvotes': upvotes 
        }
    )


def flag(request, object, object_id):
    if not request.user.is_authenticated:
        return JsonResponse({'redirect': '/account/login/'}, status=401)
    if object == 'post':
        post = get_object_or_404(Post, id=object_id)
        flag = Flag.objects.filter(user=request.user, post=post).first()
    elif object == 'comment':
        comment = get_object_or_404(Comment, id=object_id)
        flag = Flag.objects.filter(user=request.user, comment=comment).first()
    else:
        return JsonResponse(status=400)
    
    if request.method == 'POST':
        reason = request.POST.get('reason')
        if not reason:
            return
        if flag:
            flag.reason = reason
            flag.save()
            return JsonResponse(
                {
                    'message': 'Flag updated successfully', 
                    'action': 'flag'
                }
            )
        else:
            if object == 'post':
                flag = Flag.objects.create(
                    user=request.user, 
                    post=post, 
                    reason=reason
                )
            elif object == 'comment':
                flag = Flag.objects.create(
                    user=request.user, 
                    comment=comment, 
                    reason=reason
                )
            return JsonResponse({'message': 'Flagged successfully', 'action': 'flag'})
    return JsonResponse({'error': 'Invalid request method'}, status=405)


def toggle_save(request, object, object_id):
    if not request.user.is_authenticated:
        return JsonResponse({'redirect': '/account/login/'}, status=401)
    if object == 'post':
        post = get_object_or_404(Post, id=object_id)
        save = Save.objects.filter(user=request.user, post=post).first()
    elif object == 'comment':
        comment = get_object_or_404(Comment, id=object_id)
        save = Save.objects.filter(user=request.user, comment=comment).first()  
    else:
        return HttpResponse(status=400)
    if save:
        save.delete() 
        return JsonResponse(
            { 
                'is_added': False, 
                'message': 'Unsaved', 
                'action': 'save'
            }
        )
    else:
        if object == 'post':
            Save.objects.create(user=request.user, post=post)
        elif object == 'comment':
            Save.objects.create(user=request.user, comment=comment)  
    return JsonResponse(
        { 
            'is_added': True, 
            'message': 'Saved', 
            'action': 'save' 
        }
    )


@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    sort_by = request.GET.get('sort', 'upvotes')
    top_level_comments = post.comments.filter(parent__isnull=True)
    sorted_comments = sort_queries(top_level_comments, sort_by, 'comment_upvotes')
    comments = paginate(request, sorted_comments)

    context = {
        "post": post,
        "comments": comments,
        'sort_by': sort_by,
    }

    return render(request, "posts/post_detail.html", context)


@login_required
def sort_comments(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    sort_by = request.GET.get('sort', 'upvotes')  
    top_level_comments = post.comments.filter(parent__isnull=True)
    sorted_comments = sort_queries(top_level_comments, sort_by, 'comment_upvotes')
    comments = paginate(request, sorted_comments) 

    interaction = user_interaction_state(request.user)
    comments_list = render_to_string('partials/comment_list.html', 
        {
            'comments': comments,
            'user': request.user,
            'csrf_token': get_token(request),
            'interaction': interaction,
        }
    )

    return JsonResponse({'comments_list': comments_list})


def create_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if not request.user.is_authenticated:
        return JsonResponse({'redirect': '/account/login/'}, status=401)

    parent_comment_id = request.POST.get('parent_comment_id')
    parent_comment = None
    if parent_comment_id:
        parent_comment = get_object_or_404(Comment, id=parent_comment_id)

    text = request.POST.get('comment_text')
    if not text or text.strip() == '':
        return JsonResponse(status=400)

    comment = Comment.objects.create(
        post=post,
        user=request.user,
        parent=parent_comment,
        text=text
    )

    comment_html = render_to_string('partials/comment.html', 
        { 
            'comment': comment, 
            'user': request.user,
            'csrf_token': get_token(request),
        }
    )

    messages.success(request, 'Comment Posted!')
    flash_message_html = render_to_string('partials/flash_message.html', 
        {
            'messages': messages.get_messages(request),
        }
    )
    
    return JsonResponse(
        {
            'flash_message_html': flash_message_html,
            'comment_html': comment_html,
            'comment_id': comment.id,
            'action': 'create'
        }
    )


def edit_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if not request.user.is_authenticated:
        return JsonResponse({'redirect': '/account/login/'}, status=401)

    comment_id = request.POST.get('comment_id')
    comment = get_object_or_404(Comment, id=comment_id, user=request.user)
    new_text = request.POST.get('edit_comment_text')

    if not new_text or new_text.strip() == '':
        return JsonResponse({'error': 'New comment is required.'}, status=400)

    comment.text = new_text
    comment.save()

    interaction = user_interaction_state(request.user)
    comment_html = render_to_string('partials/comment.html', 
        { 
            'comment': comment,  
            'user': request.user,
            'csrf_token': get_token(request),
            'interaction': interaction,
        }
    )

    messages.success(request, 'Comment Edited!')
    flash_message_html = render_to_string('partials/flash_message.html', 
        {
            'messages': messages.get_messages(request),
        }
    )

    return JsonResponse(
        {
            'flash_message_html': flash_message_html,
            'comment_html': comment_html,
            'comment_id': comment.id,
            'action': 'edit'
        }
    )


def delete_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if not request.user.is_authenticated:
        return JsonResponse({'redirect': '/account/login/'}, status=401)

    comment_id = request.POST.get('comment_id')
    comment = get_object_or_404(Comment, id=comment_id, user=request.user)
    comment.delete()

    messages.success(request, 'Comment Deleted!')
    flash_message_html = render_to_string('partials/flash_message.html', 
        {

posts/templates/posts/all_posts.html
{% extends 'base.html' %}
{% block 'title' %} All Posts {% endblock %}
{% block 'main' %} 
{% include "partials/flash_message.html" %}
{% include "acc_partials/profile_overview.html" %}
<section class="overview-posts">
    <div class="container">
        <h2>{{ user.username }}'s Posts ({{ total_posts }})</h2>
        <form method="GET" action="{% url 'posts:all_posts' user.id %}">
            {% include "partials/sort.html" %}
        </form>
        {% for post in posts %}
        <div class="posts">
            {% include "partials/post.html" with truncate=True %}
            <hr>
        </div>
        {% empty %}
        <p>You have not posted</p>
        {% endfor %}
    </div>
</section>
{% include "partials/pagination.html" %}
{% endblock %}

posts/templates/posts/category.html
{% extends 'base.html' %}
{% block 'title' %}Category:{{ category }}{% endblock%}
{% block 'main' %}
{% include "partials/flash_message.html" %}
<section class="overview-posts">
    <div class="container">
        <h2>{{ category }} ({{ total_posts }})</h2>
        {% for post in posts %}
        <div class="posts">
            {% include "partials/post.html" %}
            <hr>
        </div>
        {% empty %}
        <p>No posts for this category</p>
        {% endfor %}
    </div>
</section>
{% endblock %}

posts/templates/posts/create_post.html
{% extends 'base.html' %} 
{% block 'title' %} Create a post {% endblock %} 
{{ form.media }}
{% block 'main' %}
{% include "partials/flash_message.html" %}
<section class="create-edit-post">
    <div class="container">
        <h2 class="title">create post</h2>
        <form method="POST" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            <p>Title: {{ post_form.title }}</p>
            <p>Select Tag/Category</p>
            <div class="tags">
                {% for choice in post_form.tags %}
                <div class="tag">
                    {{ choice.tag }}
                    <label for="{{ choice.id_for_label }}"
                        >{{ choice.choice_label }}
                    </label>
                </div>
                {% endfor %}
            </div>
            {{ post_form.content }} 
            <div class="media-input-container">
                <div class="wrapper">
                    <label class="media-label" for="id_media">
                        <i class="fa-solid fa-cloud-arrow-up"></i> 
                        Drag and Drop or upload media
                    </label>
                    {{ media_form.media }}
                    <div class="media-preview"></div>
                    <div class="file-name-preview"></div>
                    <button
                        id="clear-media"
                        class="clear-media-btn"
                        style="display: none"
                    >
                        <i class="fa-solid fa-trash-can"></i>
                    </button>
                </div>
            </div>
            <p>Link{{ post_form.url }}</p>
            <div class="btn-container">
                <button class="blue-btn" type="submit">Post</button>
                <a class="cancel-btn" href="javascript:history.back()">Cancel</a>
            </div>
        </form>
    </div>
</section>
{% endblock %}

posts/templates/posts/delete_post.html
<h2>Are you sure? all related data to this post will be permanently deleted</h2>
<p>{{ post.title }}</p>
<form method="POST"  action="{% url 'posts:delete_post' post_id=post_id %}">
{% csrf_token %}
    <div class="btn-container">
        <a class="cancel-btn" id="close-btn">Cancel</a>
        <button class="blue-btn" type="submit">Yes, delete it</button>
    </div>
</form>

posts/templates/posts/edit_post.html
{% extends 'base.html' %} 
{% block 'title' %} Edit a post {% endblock %} 
{% block 'main' %}
{% include "partials/flash_message.html" %}
<section class="create-edit-post">
    <div class="container">
        <h2 class="title">Edit post</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <p>Title: {{ post_form.title }} </p>
            <p>Select Tags/Category</p>
            <div class="tags">
                {% for choice in post_form.tags %}
                    <div class="tag">
                        {{ choice.tag }}
                        <label for="{{ choice.id_for_label }}">{{ choice.choice_label }}</label>
                    </div>   
                {% endfor %}
            </div>
            {{ post_form.content }}
            <div class="media-input-container">
                <div class="wrapper">
                    <label class="media-label" for="id_media">
                    <i class="fa-solid fa-cloud-arrow-up"></i> Drag and Drop or upload media
                    </label>
                    {{ media_form.media }}
                    <div class="media-preview">{% include "partials/media_post.html" %}</div>
                    <div class="file-name-preview">
                        {% if media_form.media.value %}
                        {{ media_form.media.value }}    
                        {% endif %}
                    </div>
                    <button id="clear-media" class="clear-media-btn">
                        <i class="fa-solid fa-trash-can"></i>
                    </button>
                </div>
            </div>
            <p>Link{{ post_form.url }}</p>
            <div class="btn-container">
                <button class="blue-btn" type="submit">Update</button>
                <a class="cancel-btn" href="javascript:history.back()">Cancel</a>
            </div>
        </form>
    </div>
</section>
{% endblock %}

posts/templates/posts/home.html
{% extends 'base.html' %} 
{% block 'title' %} Home {% endblock %} 
{% block 'main' %}
{% include "partials/flash_message.html" %}
<section class="post">
    <div class="container">
        <div class="posts">
            {% if posts %}
            {% for post in posts %}
            {% include "partials/post.html" with truncate=True %}
            <hr>
            {% endfor %}
            {% else %}
            <p>No posts here</p>
            {% endif %}
        </div>
    </div>
</section>
{% include "partials/pagination.html" %}
{% endblock %}

posts/templates/posts/liked_comments.html
{% extends 'base.html' %} 
{% block 'title' %} Liked Comments {% endblock %} 
{% block 'main' %}
{% include "partials/flash_message.html" %}
{% include "acc_partials/profile_overview.html" %}
<section class="overview-posts">
    <div class="container">
        <h2>Liked Comments ({{ total_likes }})</h2>
        <form method="GET" action="{% url 'posts:liked_comments' %}">
            {% include "partials/sort.html" %}
        </form>
    </div>
</section>
{% for comment in comments %}
{% include "partials/comment_search.html" %}
{% endfor %}
{% include "partials/pagination.html" with posts=comments %}
{% endblock %}

posts/templates/posts/liked_posts.html
{% extends 'base.html' %} 
{% block 'title' %} Liked Posts {% endblock %} 
{% block 'main' %}
{% include "partials/flash_message.html" %}
{% include "acc_partials/profile_overview.html" %}
<section class="overview-posts">
    <div class="container">
        <h2>Liked Posts ({{ total_liked_posts }})</h2>
        <form method="GET" action="{% url 'posts:liked_posts' %}">
            {% include "partials/sort.html" %}
        </form>
    </div>
</section>
{% if posts %}
{% for post in posts %}
{% include "partials/post_search.html" %}
{% endfor %}
{% include "partials/pagination.html" %}
{% endif %}
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %} 
{% block 'title' %} {{ post.title }} {% endblock %} 
{% block 'main' %}

<div class="target-container">
{% include "partials/flash_message.html" %}   
</div>

<section class="post">
    <div class="container">
        <div class="posts">
            <a 
                class="back-btn details-page btn-yellow" 
                href="javascript:history.back()">
                <i class="fa-regular fa-circle-left"></i> 
                Back
            </a>
            {% include "partials/post.html" %}
            <hr>
        </div>
    </div>
</section>

<section class="comment-section">
    <div class="container">
        <div>
            <form 
                method="POST"
                action="{% url 'posts:create_comment' post.id %}"
                class="create-comment action-form">
                {% csrf_token %}
                <input type="text" name="comment_text" required placeholder="Enter your comment">
                <button class="blue-btn" type="submit" name="create_comment">comment</button>
            </form>
            <form 
                method="GET" 
                action="{% url 'posts:post_detail' post.id %}">
                {% include "partials/detail_sort.html" %}
            </form>
            <ul 
                id="comments-list"
                data-post-id="{{ post.id }}">
                {% for comment in comments %}
                <div>
                    {% include "partials/comment.html" %}
                </div>    
                {% endfor %}
            </ul>
        </div>
    </div>
</section>
{% include "partials/pagination.html" with posts=comments %}
{% endblock %}

posts/templates/posts/saved_comments.html
{% extends 'base.html' %} 
{% block 'title' %} Saved Comments {% endblock %} 
{% block 'main' %}
{% include "partials/flash_message.html" %}
{% include "acc_partials/profile_overview.html" %}
<section class="overview-posts">
    <div class="container">
        <h2>Saved Comments ({{ total_saved_comments }})</h2>
        <form method="GET" action="{% url 'posts:saved_comments' %}"> 
            {% include "partials/sort.html" %}
        </form>
    </div>
</section>
{% for comment in comments %}
{% include "partials/comment_search.html" %}
{% endfor %}
{% include "partials/pagination.html" with posts=comments %}
{% endblock %}

posts/templates/posts/saved_posts.html
{% extends 'base.html' %} 
{% block 'title' %} Saved Posts {% endblock %} 
{% block 'main' %}
{% include "partials/flash_message.html" %}
{% include "acc_partials/profile_overview.html" %}
<section class="overview-posts">
    <div class="container">
        <h2>Saved Posts ({{ total_saved_posts }})</h2>
        <form method="GET" action="{% url 'posts:saved_posts' %}">
            {% include "partials/sort.html" %}
        </form>
    </div>
</section>
{% if posts %}
{% for post in posts %}
{% include "partials/post_search.html" %}
{% endfor %}
{% include "partials/pagination.html" %}
{% endif %}
{% endblock %}

posts/templates/posts/search_result.html
{% extends 'base.html' %}
{% block 'title' %}Search Results{% endblock %}
{% block 'main' %}
{% include "partials/flash_message.html" %}
{% load custom_filters %}
<section>
    <div class="container">
        <h2>Total results ({{ total_results }})</h2>  
    </div>
</section>
{% if page %}
{% for result in page %}
{% if result|is_post %}
{% include "partials/post_search.html" with post=result %}
{% endif %}   
{% if result|is_comment %}    
{% include "partials/comment_search.html" with comment=result %}
{% endif %}
{% endfor %}
<section class="pagination">
    <div class="container">
                <span class="step-links">
                    <div>
                        {% if page.has_previous %}
                        <a class="blue-btn" href="?query={{ query }}&sort={{ sort_by }}&page=1">&laquo; first</a>
                        <a class="blue-btn" href="?query={{ query }}&sort={{ sort_by }}&page={{ page.previous_page_number }}">previous</a>
                    {% endif %}
                    </div>
                    
                    {% if page.has_previous or page.has_next %}
                    <span class="current">
                        Page {{ page.number }} of {{ page.paginator.num_pages }}
                    </span>
                    {% endif %}

                    <div>
                        {% if page.has_next %}
                        <a class="blue-btn" href="?query={{ query }}&sort={{ sort_by }}&page={{ page.next_page_number }}">next</a>
                        <a class="blue-btn" href="?query={{ query }}&sort={{ sort_by }}&page={{ page.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                    </div>
                    
                    
                </span>
            </div>
        </section>
    {% endif %}

    {% if not page %}
        <div class="container">
            <h3>No result for: "{{ query }}"</h3>
        </div>
    {% endif %}

{% endblock %}